title: 'Whats up Isha'
description: 'Community of Ishaites to share information, giveaway items and ask questions'
baseurl: '/iyc'
url: ''
github_user: 'pocha'
github_branch: 'master'

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

collections:
  topics:
    output: true
    permalink: /topic/:name/

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      permalink: /post/:title/
      layout: 'post'
  - scope:
      path: ''
      type: 'topics'
    values:
      layout: 'topic'

# Exclude image files from processing
exclude:
  - '**/*.png'
  - '**/*.jpg'
  - '**/*.jpeg'
  - '**/*.gif'
  - '**/*.svg'
  - '**/*.webp'
