title: 'Whats up Isha'
description: 'Community of Ishaites to share information, giveaway items & ask questions'
baseurl: '/iyc'
url: ''

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

collections:
  topics:
    output: true
    permalink: /topic/:name/

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
  - scope:
      path: ''
      type: 'topics'
    values:
      layout: 'topic'
